# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e81b1815fa0b8e0e92bb13c022a66ab46aed10504ae97b3da36f226fcc38918c1667a7b31a3cac1bab500c4234d7ff9c9dcf7b0484a8c206e647627d1e565bda

test:
  secret_key_base: d632e42d17f1ef0a9b4fa344fb4b107fe3b377731564f34a795c0124708bf682e217522dc79e4a55d91bde1853a73c538247f3a254dfc3114eaa79311c3e9681

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
